README.md

Jurgen Schmidhuber and his students influenced a lot the field, mainly with LSTMs and winning competitions with deep convents. I believe his perspective on the subject should be highly considered.

added Jurgen Schmidhuber's book to the list

---

README.md

Chainer is a nice framework of Neural Networks

Added Chainer

---

README.md

Added links to a deep learning news site (hacker news style) and a RNN library.

Added a few links.

---

README.md

Good digit recognition repository for beginners and learning

Added basic digit recognition good for learning

---

README.md

Added Nat & Lo's  beginners Guide to Deep Neural Networks

A beginners Guide to Deep Neural Networks

---

README.md

Add three deep learning frameworks, namely MXnet, Veles and Marvin.

add some frameworks

---

README.md

Add Apache SINGA platform

---

README.md

Deep learning course by University of Waterloo

UWaterloo Deep Learning course

---

README.md

Data generated from the paper ["Teaching Machines to Read and Comprehend"](http://arxiv.org/abs/1506.03340).

Add DeepMind QA corpus

---

README.md

It is a scalable Machine Learning library written in c++ with Neural Network support.

added mlpack

---

README.md

Good classroom course by Larry Wasserman at CMU

An ML course and a recent deep learning paper

---

README.md

I made an awesome list of most cited deep learning papers.
https://github.com/terryum/awesome-deep-learning-papers
I'm not sure if my edition is a good way to introduce the repo, but I'd like to introduce this repo in a some way through this list.
Thank you.
Terry

Add "Awesome deep learning papers"

---

README.md

Good deep learning course by Yann LeCun

Added DL course by Yann LeCun

---

README.md

Update Torch7 tutorials link

---

README.md

Hi,
I created a pull request adding the link of the "UVA DeepLearning Course" at University of Amsterdam. The course is still going and content is getting added. First week lecture video, slides and practicals are already available.

Adding UVA Deep Learning Course

---

README.md

Added Machine Learning is Fun! Medium Article

Added article on Machine Learning and Deep Learning

---

README.md

MIT 6.S094: Deep Learning for Self-Driving Cars

MIT 6.S094: Deep Learning for Self-Driving Cars

---

README.md

Added the following awesome blog ; https://medium.com/@ageitgey/

Adding 'Machine Learning is Fun!' Blog

---

README.md

Add Keras video course link.
Fix markdown syntax of some course links.

Add Keras course

---

README.md

I fixed some links that were being displayed incorrectly due to some markdown typos.

Fix links that were being displayed incorrectly

---

README.md

[CNTK - Microsoft Cognitive Toolkit](https://github.com/Microsoft/CNTK)

added CNTK to Frameworks section

---

README.md

**[Insert the URL to be listed]**
https://github.com/natanielruiz/dockerface
**[Explain what the project is about and why it should be listed]**
Dockerface is an easy to install and use deep learning face detection for images and video in a docker container. It is meant for research and open for industry and personal use. It deploys a trained Faster R-CNN network on Caffe through an easy to use docker image. Bring your videos and images, run dockerface and obtain videos and images with bounding boxes of face detections and an easy to use face detection annotation text file.
I also created a new section called Machine Learning. Docker is widely used in the field so it might make more people submit this style of applications to the list.
Cheers!
Nataniel

Added Dockerface

---

README.md

A beginner's tutorial to create a content based image retrieval system using a convolutional denoising autoencoder

Keras Tutorial: CBIR Using an Autoencoder

---

README.md

Added a course list to the Deep Learning coursework.

Updating Readme - course list update

---

README.md

[Serpent.AI](https://github.com/SerpentAI/SerpentAI) is a simple yet powerful, novel framework to assist developers in the creation of game agents. Turn ANY video game you own into a sandbox environment ripe for experimentation, all with familiar Python code. The framework's raison d'être is first and foremost to provide a valuable tool for Machine Learning & AI research. It also turns out to be ridiculously fun to use as a hobbyist (and dangerously addictive; a fair warning)!

Add Serpent.AI to Frameworks

---

README.md

I have included a list of 11 conferences. Will add more in future

Included conferences

---

README.md

a web series on deep learning (new video every week in Spring 2018)

added Deep Learning Crash Course

---

README.md

Added online book having topic wise detailed explanation.

added AI/ML topic-wise explanation

---

README.md

Two additions for Reinforcement Learning frameworks:
- **TensorForce**: https://github.com/reinforceio/tensorforce
- **NervanaSystems Coach**: https://github.com/NervanaSystems/coach

Additions to RL frameworks

---

README.md

The repository contains research papers with implementations on tools that learn representations of whole graphs.

Added graph embeddings awesome repository.

---

README.md

New course by Andrew Ng — AI for Everyone by Andrew Ng on his website https://deeplearning.ai

New course by Andrew Ng — AI for Everyone

---

README.md

Also modified text of graph embedding to differentiate between the two repositories.

Added awesome network embedding.

---

README.md

Fix simple typo: engineerign -> engineering

---

README.md

* added Neptune: experiment tracking tool

added Neptune: experiment tracking tool

---

README.md

Added Google's brand new course on machine learning with tensor flow APIs part of learn witb Google AI series of educational content

Added Google's brand new course

---

README.md

Added Machine Learning for Mere Mortals to course section

---

README.md

Karate Club consists of state-of-the-art methods to do unsupervised learning on graph structured data. To put it simply it is a Swiss Army knife for small-scale graph mining research. First, it provides network embedding techniques at the node and graph level. Second, it includes a variety of overlapping and non-overlapping community detection methods. Implemented methods cover a wide range of network science (NetSci, Complenet), data mining (ICDM, CIKM, KDD), artificial intelligence (AAAI, IJCAI) and machine learning (NeurIPS, ICML, ICLR) conferences, workshops, and pieces from prominent journals.

Karate Club is an unsupervised machine learning for graphs

---

README.md

The graph embedding link was dead.

Fixed dead link.

---

README.md

[Catalyst framework](https://github.com/catalyst-team/catalyst) was developed with a focus on reproducibility, fast experimentation and code/ideas reusing. Being able to research/develop something new, rather than write another regular train loop.
**Features**
- Universal train/inference loop.
- Configuration files for model/data hyperparameters.
- Reproducibility – all source code and environment variables will be saved.
- Callbacks – reusable train/inference pipeline parts.
- Training stages support.
- Easy customization.
- PyTorch best practices (SWA, AdamW, 1Cycle, FP16 and more).
**Structure**
- DL – runner for training and inference, all of the classic machine learning and computer vision metrics and a variety of callbacks for training, validation, and inference of neural networks. …

Add Catalyst framework

---

README.md

> Code Machine Learning Pipelines - The Right Way.
Neuraxle is a framework for building neat pipelines, providing the right abstractions to both ease research, development, and deployment of your ML applications.
> Production-ready.
Most research projects don't ever get to production. However, you want your project to be production-ready and already adaptable (clean) by the time you finish it. You also want things to be simple so that you can get started quickly.
Most existing machine learning pipeline frameworks are either too simple or too complicated for medium-scale projects. Neuraxle is balanced for medium-scale projects, providing simple, yet powerful abstractions that are ready to be used.
Refer to: 
- https://www.neuraxle.neuraxio.com/stable/index.html
- …

Add Neuraxle

---

README.md

https://mrdimosthenis.github.io/Synapses

Add Synapses to Frameworks section

---

README.md

Hi!
I thought this video might be great adding to your list of live videos and courses about deep learning.
Please, let me know what you think about it.
Thank you for your consideration. 
Rada.

adding to your list of videos and lectures

---

README.md

Easy and in very simple words explanation of CNN for a new person.

Added wesbite for CNN

---

README.md

Hello there,
Can you please consider adding this video to your library? If you are interested we can provide complimentary copy for you.
Thank you so much.

Added Deep Learning Crash Course Video

---

README.md

Merve Ayyüce Kızrak is co-founder of Deep Learning Turkey. She has also a course in Udemy, explains Deep Learning very well.
Hakan Cebeci is a Udemy instructor who has courses for NLP and Deep Learning(Over CNN).

One researcher and course added.

---

README.md

Please kindly review and add these two blog posts I wrote on deep learning

adding my blog

---

README.md

@ChristosChristofidis @ChaiBapchya  I have added 2 articles on self-supervised learning and the ALBERT model. Please review the pull request and merge it.  Thanks.
[![image](https://user-images.githubusercontent.com/8587189/75771494-33817b00-5d72-11ea-98a1-6dd618060d71.png)](https://amitness.com/2020/02/illustrated-self-supervised-learning/)
[![image](https://user-images.githubusercontent.com/8587189/75771532-4431f100-5d72-11ea-9623-734d8e7275b2.png)](https://amitness.com/2020/02/albert-visual-summary/)

Add articles on self-supervised learning and albert model

---

README.md

Hi, 
I've added two significant research papers in the papers section. Please look into it.

Added two research papers

---

README.md

AI Summer contains lots of articles on Deep Learning algorithms, including both intuitive explanations and practical programming examples. So it might be a good addition to this amazing list of resources.
Disclaimer: I'm the author

Add AI Summer blog

---

README.md

Hi,
I am Branko from Manning Publications.
I though this great early-access book might be a good fit for your repo.
Thanks for considering it!

added Math and Architectures of Deep Learning

---

README.md

Hi! This is my first pull request ever. I have added 4 deep learning channels namely
CS 229 (Machine Learning Andrew Ng) 2018 version
DeepMind X UCL Intro to deep learning series released 2020
DeepMind X UCL Reinforcement Learning (Deep RL) 2018 version
CMU 11-785 Intro to deep learning by Bhiksha Raj 2020 - Great lectures.

Added 4 Latest Deep Learning series recently released on Youtube

---

README.md

AIHub.org website added - supported by AAAI, NeurIPS, ICML

Added AIHub dot org website

---

README.md

Added two courses, Intro to Deep Learning with PyTorch by FacebookAI and Deep Learning by Kaggle.

Add some courses

---

README.md

Hi,
Would like to release a new book released by Manning "TensorFlow 2.0 in Action".
Thank you.

Added TF2 in Action

---

README.md

Roadmap to becoming an Artificial Intelligence Expert

Added AI Expert Roadmap

---

README.md

Hi,
Branko from Manning here, I thought this liveProject tutorial that we published could be a valuable resource here.
Thanks for checking it out!

added Semi-Supervised Deep Learning with GANs for Melanoma Detection

---

README.md

Hi there,
I would like to add some state-of-the-art to the awesome DL repo

Some recent state-of-the-art 

---

README.md

It is a quite efficient and easy-to-use training system of large AI models. With changing several lines of code, I can start efficient distributed training. I believe it's worth a try. :)

Add an Awesome and Easy-to-use System for Large-scale AI Model Training

---

README.md

Hi, 
Stjepan from Manning here. I thought this title might be a good match for your list. Thank you for considering it.
Best,

Added Deep Learning for NLP

---

README.md

Awesome overview! 😎 I am adding four question answering datasets and a neural search framework to update the NLP & DL part of the list.

Add question answering datasets

---

README.md

Added the deep reinforcement learning framework [Maze](https://github.com/enlite-ai/maze). Disclaimer: I'm one of the maintainers.

Added deep reinforcement learning framework Maze

---

README.md

Hub - Fastest unstructured dataset management for TensorFlow/PyTorch by activeloop.ai. Stream & version-control data. Converts large data into a single numpy-like array on the cloud, accessible on any machine.
Describe features.
- Store and retrieve large datasets with version-control
- Collaborate as in Google Docs: Multiple data scientists working on the same data in sync with no interruptions
- Access from multiple machines simultaneously
- Deploy anywhere - locally, on Google Cloud, S3, Azure, and Activeloop (by default - and for free!)
- Integrate with your ML tools like Numpy, Dask, Ray, PyTorch, or TensorFlow
- Create arrays as big as you want. You can store images as big as 100k by 100k!
- Keep the shape of each sample dynamic. This way you can store small and big arrays as 1 …

Added hub to the list
